spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  ACCESS_KEY_ID: LTAI5tKdDpEHNdP6p8KqAPEy
  SECRET_ACCESS_KEY: k8opWlvHvYNlegA05tuLaj0csNdLKC